# Generated by Django 5.1.5 on 2025-01-27 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exam_alter_user_avatar_session_sessionnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam'),
        ),
    ]
